# Generated by Django 4.2.1 on 2023-08-17 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invited_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
