version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: andruce/authorization_backend
    env_file: .env
    depends_on:
      - db
  
  gateway:
    image: andruce/authorization_gateway
    env_file: .env
    ports:
      - 8000:80
